### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by sagitt** [colagrosso/avviso#13]
i'm trying it, using yout example sketch and won't work.

**Comment by colagrosso** [comment]
Hi, thanks for trying Avviso, and I'm sorry it doesn't work for you. The project has been unmaintained for years now. It's very likely that Avviso isn't compatible with a recent Arduino IDE. In order to diagnose the problem, we'd need more details, e.g., version of Arduino you're using, any error messages, etc.

**Comment by sagitt** [comment]
first one, need to update http library (prowl on twitter say this)
i'm using arduino mega with ethernet shield, IDE 1.9.0 beta
i'm pro user, i create my own sketch (1000+ lines), i found different solution but your sketch won't work

in specific, don't go after Avviso.begin()..... so loop won't start
and the ethernet library need ip address (for me)

**Comment by colagrosso** [comment]
OK, thanks for the extra details. The last version of the IDE that I've got Avviso working with is 1.0, so version 1.9.0 beta is well beyond that. 

Like a wrote above, this project has been unmaintained for years, and my last commit was in 2012. I wrote this in the project description, too. If you'd like to send a pull request for updating the HTTP library or other changes, I'd be happy to review them.
